### ISSUE TITLE
Syntax highlighting doesn't work

### ISSUE THREAD

**Issue by jliptrap** [Isti115/agda.nvim#1]
There's no syntax highlighting when I open an agda file.  Compilation seems to be working though.

For reference, syntax highlighting works with [vim-agda](https://github.com/msuperdock/vim-agda).  I had been overriding its syntax highlighting with a `~/.config/nvim/syntax/agda.vim` file, but that doesn't work with `agda.nvim`.

I'm using Neovim 0.5.1, Agda 2.6.2, and vim-plug.

**Comment by jliptrap** [comment]
I'm on gnome-terminal 3.38.1, but I tried kitty and it didn't help.

Meanwhile I got the syntax highlighting override to work by adding the `setfiletype` [invocation](https://github.com/msuperdock/vim-agda/blob/6f86a7ef/ftdetect/agda.vim) to my `init.vim`.

**Comment by isti115** [comment]
Syntax highlighting is usually not done syntactically for Agda, rather semantically, meaning that it is not based on RegEx rules and such, but instead the information comes back from the `agda` executable while typechecking, that's why you don't see any highlighting before you load a file. That's pretty normal, it works the same way in Emacs and VSCode as well (I would assume Atom too, but it's been a long time since I've used that), but I have added a few rules (keywords and comments) that can be hardcoded.

Agda syntax is really unpredictable, as apart from a few reserved operators practically any character can be used in identifiers and there is no clear distinction between record field, data constructors, etc. in terms of naming, but hopefully with something like this: https://github.com/tree-sitter/tree-sitter-agda we could get decent coloring at some point later even before loading the file.

**Comment by jliptrap** [comment]
`agda.nvim`'s syntax highlighting isn't triggering for me even after loading a file.

(Currently not a big issue for me as the highlighting override works fine for the code I'm dealing with, because it assumes tame identifiers.)

**Comment by jliptrap** [comment]
Until coloring before loading is supported, I think some users would prefer to use vim-agda's approach to highlighting, so it would be useful if agda.nvim had an option to disable its highlighting.

**Comment by jliptrap** [comment]
In particular, I would find it useful if there were an option to disable HighlightingInfo [handling](https://github.com/Isti115/agda.nvim/blob/672da23557310354d326eaaee68538398ed3461c/lua/agda/response.lua#L144).

**Comment by Geometer1729** [comment]
Same here no syntax highlighting what so ever. Not even comments.

**Comment by isti115** [comment]
This is very strange. :open_mouth: Do holes and such appear properly though? If yes, I have an idea! :bulb: The problem might be that I'm using rgb values instead of the xterm 256 color palette.
Try enabling [`termguicolors`](https://neovim.io/doc/user/options.html#'termguicolors')!

**Comment by Geometer1729** [comment]
Yo that fixed it! Thanks so much!

**Comment by isti115** [comment]
@Geometer1729 Great! :+1: 
@jliptrap Does the same fix work for you as well?
Please close the issue if the solution has been found! :slightly_smiling_face:

**Comment by jliptrap** [comment]
Works for me too, thanks!  I'd recommend mentioning `termguicolors` in the README.
