### ISSUE TITLE
C style comments

### ISSUE THREAD

**Issue by jliptrap** [Isti115/agda.nvim#3]
Using [commentary.vim](https://github.com/tpope/vim-commentary), the `gcc` command comments out a line `/* like this */`.  So looks like the vim variable `commentstring` isn't being set.

**Comment by isti115** [comment]
Yes, I had already noticed this, but have since forgotten about it, thanks for bringing it to my attention!  
I have added the correct `commentstring` value.

**Comment by jliptrap** [comment]
Hmm now `gcc` doesn't do anything.

**Comment by jliptrap** [comment]
`vim-agda`'s [comment setting](https://github.com/msuperdock/vim-agda/blob/6f86a7efdb/ftplugin/agda.vim) works for `agda.nvim` too.

**Comment by isti115** [comment]
Hmm, sorry for the long delay this time around, I'll try to tackle some of the issues today!
I have realized, that the comments started working for me not because I set the `commentstring`, but because I added filetype detection and that in turn made `tcomment` (the comment plugin that I've been using for a long time, but I should probably switch to something more modern, preferably written in Lua) use the right comment type, as it has agda support built in: https://github.com/tomtom/tcomment_vim/search?q=agda

**Comment by isti115** [comment]
@jliptrap Does it work for you now? Please close the issue if it does! :slightly_smiling_face: 
(I don't want to do it without confirmation this time, it didn't work out that well last time. :upside_down_face:)

**Comment by jliptrap** [comment]
It works, thanks!  :)
